# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "supermodel"
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex MacCaw"]
  s.date = "2012-10-18"
  s.description = "In memory DB using ActiveModel"
  s.email = "info@eribium.org"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "lib/super_model.rb",
    "lib/supermodel.rb",
    "lib/supermodel/association.rb",
    "lib/supermodel/base.rb",
    "lib/supermodel/callbacks.rb",
    "lib/supermodel/dirty.rb",
    "lib/supermodel/ext/array.rb",
    "lib/supermodel/marshal.rb",
    "lib/supermodel/observing.rb",
    "lib/supermodel/random_id.rb",
    "lib/supermodel/redis.rb",
    "lib/supermodel/timestamp.rb",
    "lib/supermodel/validations.rb",
    "lib/supermodel/validations/uniqueness.rb",
    "supermodel.gemspec"
  ]
  s.homepage = "http://github.com/maccman/supermodel"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.19"
  s.summary = "In memory DB using ActiveModel"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, ["~> 3.2.0"])
    else
      s.add_dependency(%q<activemodel>, ["~> 3.2.0"])
    end
  else
    s.add_dependency(%q<activemodel>, ["~> 3.2.0"])
  end
end

